# Generated by Django 3.2.16 on 2025-05-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='cart_user_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['recipe'], name='cart_recipe_idx'),
        ),
    ]
